name: Create PR message

on:
  pull_request:
    branches: [master]
  pull_request_review:
    types: [submitted]

jobs:

  test:
    name: Run a demo test
    runs-on: ubuntu-latest
    steps:

      - name: set api key
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN
          echo $TEST_API_KEY
          if [[ -z $TEST_API_KEY ]]; then
            echo $GITHUB_TOKEN
            TEST_API_KEY=$GITHUB_TOKEN
            echo $TEST_API_KEY
          fi
          mkdir -p ~/.config/lftools/
          echo "[github]" >>  ~/.config/lftools/lftools.ini
          echo "token = $TEST_API_KEY" >>  ~/.config/lftools/lftools.ini
          echo "[github.lfit-sandbox]" >>  ~/.config/lftools/lftools.ini
          echo "token = $TEST_API_KEY" >>  ~/.config/lftools/lftools.

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          git clone "https://gerrit.linuxfoundation.org/infra/releng/lftools"
          cd lftools
          pip install .

      - name: main
        run: |
          mkdir -p artifacts
          cat > artifacts/message.md <<EOF
          # Test Message
          You must ask the current committer listed in the INFO file
          to approve this change, once enough approvals are submitted
          the pull request will automatically submit..

          Note that there are no secrets exposed in this test...

          <details>
          <summary>PR to merge $GITHUB_HEAD_REF $GITHUB_SHA -> $GITHUB_BASE_REF</summary>

          \`\`\`
          $(env | sort)
          \`\`\`

          </details>
          EOF

          foo=$(lftools github votes lfit-sandbox self-service-committer-management 9)
          echo $foo >> artifacts/message.md

      - name: Save PR message as artifact
        uses: actions/upload-artifact@v1
        with:
          name: pr_message
          path: artifacts
